name: Validate PR
on:
  pull_request:
    branches: [ master ]
jobs:
  check_formatting:
    runs-on: ubuntu-latest
    name: Check Formatting & Run Tests
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Build devcontainer
        run: docker build -t local ${{ github.workspace }}/.devcontainer

      - name: Check formatting
        run: >
          docker run -i
          -v $PWD:/srv
          -w /srv
          local
          /bin/bash -c "
          dotnet tool restore;
          dotnet csharpier --check .;
          "

      - name: Run Tests
        run: >
          docker run -i
          -v $PWD:/srv
          -w /srv
          --user=vscode
          local
          /bin/bash -c "
          dotnet build -c Release;
          ls -al;
          cat /etc/passwd;
          cd Tests;
          ./run-tests.sh;
          "
